name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.19.5"

      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run: mix escript.build
      - run: escript ./elv version
